---

- hosts: localhost
  become: true
  tasks:
    - name: add vscodium apt key
      apt_key:
        url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        state: present
        
    - name: add vscodium apt repo
      apt_repository:
        repo: deb https://download.vscodium.com/debs vscodium main
        state: present
        filename: vscodium.list

    - name: add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: add docker apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
        state: present
        filename: docker.list

    - name: update apt cache
      apt:
        update_cache: yes
        
    - name: install vscodium and docker
      package:
        name:
          - codium
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin          
        state: present

    - name: add macm to docker group
      user:
        name: macm
        groups: docker
        append: yes      

    - name: download k3d install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/rancher/k3d/main/install.sh
        dest: /tmp/install_k3d
        mode: 'u+rwx,g+rx,o+rx'

    - name: install k3d
      script: /tmp/install_k3d

    - name: download helm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/install_helm
        mode: 'u+rwx,g+rx,o+rx'

    - name: install helm
      script: /tmp/install_helm

    - name: install kubectl
      ansible.builtin.get_url:
        # url: https://dl.k8s.io/release/stable.txt
        url: https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 'u+rwx,g+rx,o+rx'

    - name: download k9s package        
      ansible.builtin.get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.30.8/k9s_linux_amd64.deb
        dest: /tmp/k9s_linux_amd64.deb

    - name: install k9s
      command: dpkg -i /tmp/k9s_linux_amd64.deb

...
